default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: joel
  port: 5432

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Blog_database

 
test:
  <<: *default
  database: Blog_database

production:
  <<: *default
  database: Blog_production
  username: Blog
  password: <%= ENV["BLOG_DATABASE_PASSWORD"] %>
